# Generated by Django 6.0.3 on 2026-03-26 02:42

import uuid

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector;'),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_alert_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('customer_id', models.CharField(db_index=True, max_length=255)),
                ('is_pep', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVESTIGATING', 'Investigating'), ('ESCALATED', 'Escalated'), ('DISMISSED', 'Dismissed'), ('AWAITING_INFO', 'Awaiting Info')], db_index=True, default='PENDING', max_length=20)),
                ('xgboost_score', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('output_snapshot', models.JSONField(default=dict)),
                ('langfuse_trace_id', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.IntegerField(default=0)),
                ('token_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='compliance_agent.alert')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_history', models.JSONField(default=list)),
                ('documents_analyzed', models.JSONField(default=list)),
                ('structured_context', models.JSONField(default=dict)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='compliance_agent.alert')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('justification', models.TextField()),
                ('anomalous_patterns', models.JSONField(default=list)),
                ('human_summary', models.TextField()),
                ('model_used', models.CharField(max_length=100)),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analysis', to='compliance_agent.investigation')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(choices=[('ESCALATE', 'Escalate'), ('DISMISS', 'Dismiss'), ('REQUEST_INFO', 'Request Info')], max_length=20)),
                ('confidence', models.FloatField()),
                ('regulations_cited', models.JSONField(default=list)),
                ('step_by_step_reasoning', models.TextField()),
                ('is_pep_override_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='compliance_agent.riskanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='RegulationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('UIAF', 'UIAF (Colombia)'), ('CNBV', 'CNBV (Mexico)'), ('SBS', 'SBS (Peru)')], db_index=True, max_length=10)),
                ('document_ref', models.CharField(max_length=255)),
                ('article_number', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('chunk_index', models.IntegerField(default=0)),
                ('gcs_uri', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_articles', models.ManyToManyField(blank=True, related_name='referenced_by', to='compliance_agent.regulationdocument')),
            ],
            options={
                'unique_together': {('document_ref', 'chunk_index')},
            },
        ),
    ]
