# Generated by Django 6.0.3 on 2026-03-28 19:41

import django.contrib.postgres.search
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compliance_agent", "0002_regulationdocument_sparse_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regulationdocument",
            name="sparse_embedding",
        ),
        migrations.AddField(
            model_name="regulationdocument",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="regulationdocument",
            index=GinIndex(
                fields=["search_vector"],
                name="regulation_search_vector_gin",
            ),
        ),
    ]
