# Generated by Django 6.0.3 on 2026-03-26 15:18

import pgvector.django.sparsevec
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulationdocument',
            name='related_articles',
        ),
        migrations.AddField(
            model_name='regulationdocument',
            name='sparse_embedding',
            field=pgvector.django.sparsevec.SparseVectorField(blank=True, dimensions=30000, null=True),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
